model 작성
fantasy-fans-ko/lad-be pull request #12
Opened 2021-11-08 11:18 UTC by juyohan

model를 작성합니다.

2021-11-08 11:53 UTC, philipjkim requested changes

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/Auction.kt
> +    var id : Long = 0L,
Kotlin 의 data class 는 기본적으로 특별한 상황이 아니면 `var` 보다는 `val` 을 사용하는 것을 권장합니다. 특정 필드의 값을 바꾸고 싶을때는 Java Value Object 의 setter 를 사용하는 방식이 아닌, 객체를 copy 하는 방식으로 특정 필드 값만 변경된 새 객체를 생성해서 사용합니다. 이렇게 해야 immutability 의 장점을 충분히 누릴 수 있어요. 

그리고 https://multifrontgarden.tistory.com/286 을 보면 JPA 를 사용하려면 data class 보다는 그냥 class 를 사용하라는 식으로 이야기하는데, 현업에서 사용해본 바에 의하면 data class 써도 전혀 불편함은 없었으니 걍 쓰시믄 될듯요.

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/BidLog.kt
> +    @ManyToOne(fetch = LAZY) @JoinColumn(name = "users_id", nullable = true)
column 명을 `users_id` -> `user_id` 로 변경해주세요.

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/BidLog.kt
> +    @ManyToOne(fetch = LAZY) @JoinColumn(name = "players_id", nullable = true)
column 명을 `players_id` -> `player_id` 로 변경해주세요.

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/Auction.kt
> +    @Column(name = "auction_name")
이미 `auctions` 라는 테이블명이 entity 에 대해 설명해주고 있으니 column 명을 `auction_name` -> `name` 으로 변경해주세요. (`auction.auctionName` 은 불필요한 중복)

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/Player.kt
> +    @NotNull @Column(name = "player_name")
column 명 앞에 `player_` 가 붙은 모든 컬럼명에서 해당 prefix 는 다 빼도 될것 같습니다. (이 entity 가 `Player` 이니까)

보통 `xxx_name` 과 같은 네이밍은 이 엔티티가 아닌 다른 엔티티의 이름을 가지고 있을때만 prefix 를 붙이는 거라고 생각하시면 됩니다.

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/Player.kt
> +    @NotNull @Column(name = "player_three")
3pt%, ft%, fg% 세 항목은 이것이 percent 값임을 컬럼명/필드명이 나타내야 합니다. 따라서 DB 컬럼명 기준으로는 `three_pct`, `fg_pct`, `ft_pct` 정도가 적절할것 같아요.

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/Player.kt
> +    var bidLogs : List<BidLog> = mutableListOf(),
var -> val 에 더불어 List 역시 `mutableListOf` 보다는 `listOf` (immutable) 를 쓰시기 바랍니다. list 변경이 필요하면 아래와 같이 객체를 새로 만들면 됩니다:

```kotlin
val bidLogAddedPlayer = player.copy(bidLogs = player.bidLogs + newBidLog)
```

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    @NotNull @Column(name = "acquisition_amount")
선수의 최종낙찰가를 의미하는 값이라면 column 명을 `price` 정도로 바꾸시면 되겠네요. (일단 `acquisition_` prefix 는 빼도 될듯요)

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    @NotNull @Column(name = "selected_num")
이 컬럼의 역할은 무엇인가요?

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    @NotNull @Column(name = "user_budget")
이 컬럼과 `acquisition_amount` 의 차이는 무엇인가요?

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    var bidLog: BidLog? = null,
BidLog 와 PlayerAcquition 의 관계가 BidLog 가 0 or 1 개의 PlayerAcquisition 을 가질 수 있는것인가요?

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/Player.kt
> +    @OneToMany(mappedBy = "player")
`@OneToMany` 를 쓰는 경우 (그리고, BidLog 쪽에는 `@ManyToOne` 으로 양쪽 모두 연관관계가 정의된 경우), 이 entity 를 `toString()` 으로 출력하면 stack overflow error 가 납니다. (무한참조 루프)

이걸 피하는 가장 쉬운 방법은 `@ManyToOne` 쪽에만 관계를 명시하고 `@OneToMany` 는 일단 선언하지 않는 것입니다. 이렇게 개발을 해나가다가 `@OneToMany` 를 선언해야하는 상황이 오면 그때 추가를 하고, 추가하면서 꼭 `@OneToMany` 가 선언된 엔티티의 `toString()` 메소드를 오버라이드해서 해당 annotation 이 걸린 필드는 toString() 에서 제외시켜야 합니다.

읽을거리: https://techblog.woowahan.com/2675/

2021-11-08 11:53 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/enumeration/PlayerStatus.kt
> +enum class PlayerStatus {
enum value 는 가급적 이해하기 쉬운 (약어가 아닌) 값으로 정의하면 좋겠어요:

```
INJURED,
OUT,
GAME_TIME_DECISION,
HEALTHY,
```

2021-11-08 12:15 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    @NotNull @Column(name = "selected_num")
selected_num은 이 선수가 해당 드래프트 내에서 몇 번째로 뽑혔는지를 알려주는 column입니다.
(하나의 드래프트만을 생각을 한다면 id의 값이 있으니 없어도 상관은 없을 듯 합니다.)

2021-11-08 12:17 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    @NotNull @Column(name = "user_budget")
acquisition_amount의 같은 경우 선수를 최종 입찰을 했을 때의 가격을 알려주는 컬럼이며, 
user_budget은 사용자가 현재 가지고 있는 금액을 알려주는 컬럼입니다.

2021-11-08 14:44 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    var bidLog: BidLog? = null,
해당 연관관계가 잘못되었네요.. 낙찰된 선수는 여러개의 로그를 가질 수 있어서 playeAc (1) : BidLog(N) 관계로 수정했습니다.

2021-11-08 14:47 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/model/Player.kt
> +    @OneToMany(mappedBy = "player")
먼저, 단방향 매핑으로 시작을 하고 추후 양방향이 필요하다면 설정을 하겠습니다!

2021-11-08 14:48 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    @NotNull @Column(name = "user_budget")
> acquisition_amount의 같은 경우 선수를 최종 입찰을 했을 때의 가격을 알려주는 컬럼이며,
> user_budget은 사용자가 현재 가지고 있는 금액을 알려주는 컬럼입니다.

결국 bid_price의 값이 acquisition_amount의 값과 중복이 되어, 해당 컬럼을 삭제하기로 결론을 내렸습니다.

2021-11-09 01:03 UTC, philipjkim requested changes

2021-11-09 01:03 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/Player.kt
> +    @NotNull @Column(name = "reb")
DB 의 column name 과 entity 의 필드명이 일치할 경우 `@Column` annotation 은 명시하지 않으셔도 됩니다. 저는 주로 `some_name` -> `someName` 과 같이 snake_case 의 컬럼명을 camelCase 필드명으로 매핑하거나 아예 컬럼명과 필드명이 달라지는 경우에만 해당 annotation 을 적어주고 있습니다.

2021-11-09 01:03 UTC, philipjkim commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
Hibernate 에게 DDL 생성/수정을 위임하는 방식은 개인적으로 권장하고 싶지 않아요. 그 이유는 Hibernate 가 만드는 DDL 은 내가 entity 에 명시한 필드 순서를 무시하고 abc 순으로 컬럼 순서를 배열해버립니다.

따라서 DDL 은 로컬환경에서도 가급적 따로 관리하고 직접 수행하는 걸 추천하고, 스키마 변경 이력을 나이스하게 관리하고 싶다면 차라리 [Flyway migration](https://engkimbs.tistory.com/795) 을 도입하시는게 나을것 같습니다.

2021-11-09 01:36 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    @NotNull @Column(name = "selected_num")
`selected_num` → `pick_number` 로 변경

2021-11-09 02:06 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/model/Player.kt
> +    @NotNull @Column(name = "reb")
@kimdg1105 
Column명을 약어로 사용하지 않고, 풀 네임으로 사용하는건 어떨까요? (to가 DB 예약어로 turn_over로 사용해야하는 상황이 생김)
`pts` → `points`

2021-11-09 02:10 UTC, juyohan commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
이 부분은 @kimdg1105 님과 이야기를 통해 확정짓고 다시 PR 받겠습니다.

2021-11-09 12:09 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/model/Player.kt
> +    @NotNull @Column(name = "reb")
@juyohan to가 있었네요. 풀네임으로 사용하는 것 동의합니다.

2021-11-09 13:31 UTC, kimdg1105 commented on src/main/resources/application.properties
> +spring.datasource.password=1234
향후 프로젝트에 있어 해당 파일을 yml로 관리하는 것은 어떨까요? 가독성 면에서 더 편한 것도 있고 관리도 편할 것 같아서 의견드립니다.

2021-11-09 14:02 UTC, juyohan commented on src/main/resources/application.properties
> +spring.datasource.password=1234
안그래도 그 부분에 있어서 한번 이야기를 나눠볼까 했습니다!
제가 혼자서 결정할 부분은 아닌 것 같아서요😅

2021-11-09 14:47 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +    @NotNull @Column(name = "user_budget")
> 제 생각에 사용자가 이 경매에서 현재 가지고 있는 금액 ($200 혹은 그 이하) 정보는 이 레코드가 아니라 (아직 이번 pr 에서는 보이지 않지만) User, Auction 관계를 가지는 entity 에 저장이 되어야 할 것 같은데, 제가 잘못 생각하고 있다면 알려주세요.

지적 감사합니다!! 확실히 따로 테이블을 두지 않는다면 현재 상황에서 사용자의 남은 값을 알려면 복잡하고 귀찮은 과정을 거쳐야하는데, 따로 테이블로 관리를 하게 된다면 좀 더 수월하겠네요!!

테이블을 많이 두지말자! 라는 생각에 사로잡혀 필요한 부분을 놓쳤던 것 같네요.

2021-11-09 14:49 UTC, juyohan commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
> Hibernate 에게 DDL 생성/수정을 위임하는 방식은 개인적으로 권장하고 싶지 않아요. 그 이유는 Hibernate 가 만드는 DDL 은 내가 entity 에 명시한 필드 순서를 무시하고 abc 순으로 컬럼 순서를 배열해버립니다.

배포를 할 땐 당연히 DDL 사용을 하지 않을 생각이었지만, 어쩌피 안쓸거 말씀하신 것처럼 그 전부터 직접 스키마를 작성하고 생성하는게 좋을 것 같네요!! 그렇게 진행하도록 하겠습니다!

2021-11-11 00:58 UTC, philipjkim commented
@juyohan 엄... 제가 아직 어제 commit 내용을 자세히 보진 못했는데, 그와 별개로 이 PR 이 reviewers 에게 approve 를 얻기 전까지는 PR 작업브랜치의 내용은 main 브랜치에 merge 하지 않는게 원칙이에요. (이걸 안하면 PR 을 만드는 이유가 없다는;;;;)

2021-11-11 01:04 UTC, juyohan commented
> @juyohan 엄... 제가 아직 어제 commit 내용을 자세히 보진 못했는데, 그와 별개로 이 PR 이 reviewers 에게 approve 를 얻기 전까지는 PR 작업브랜치의 내용은 main 브랜치에 merge 하지 않는게 원칙이에요. (이걸 안하면 PR 을 만드는 이유가 없다는;;;;)

main 브랜치가 아니라 해당 브랜치에 merge를 해놓은 겁니다!! 제가 어제 해당 브랜치에 commit을 하고나서 분할 커밋이 아니라 한번에 commit을 해버려서 `feature/init-setting` 브랜치에서 commit 삭제한 내역 가져와서 merge 한겁니다!!

2021-11-11 01:12 UTC, philipjkim commented
> > @juyohan 엄... 제가 아직 어제 commit 내용을 자세히 보진 못했는데, 그와 별개로 이 PR 이 reviewers 에게 approve 를 얻기 전까지는 PR 작업브랜치의 내용은 main 브랜치에 merge 하지 않는게 원칙이에요. (이걸 안하면 PR 을 만드는 이유가 없다는;;;;)
> 
> main 브랜치가 아니라 해당 브랜치에 merge를 해놓은 겁니다!! 제가 어제 해당 브랜치에 commit을 한 뒤, 잘못 commit을 해버려서 commit을 삭제했습니다. 그랬더니 파일들이 다 날라가는 상황이 생겼네요. 그래서 `feature/init-setting` 브랜치에서 commit 삭제한 내역 가져와서 merge 한겁니다!! 제가 main 브랜치에 `merge`를 한 줄 알고 깜짝 놀라서 확인해봤네요...

아하 그렇군요 ㅋㅋ 혹시 커밋을 잘못했을땐(push 까지도 했다면) 이전 커밋으로 돌아가서 force push 하는 것도 방법이에요. (main 브랜치에서만 이런짓 안하면 됨 ㅋㅋ)

2021-11-11 01:15 UTC, juyohan commented
> 아하 그렇군요 ㅋㅋ 혹시 커밋을 잘못했을땐(push 까지도 했다면) 이전 커밋으로 돌아가서 force push 하는 것도 방법이에요. (main 브랜치에서만 이런짓 안하면 됨 ㅋㅋ)

오... 그러네요! 다음에 똑같은 일이 발생되면 한번 이전 커밋으로 돌아가서 푸쉬하고 땡겨와봐야겠네요! 좋은 방법 감사합니다

2021-11-11 01:45 UTC, juyohan commented
`Player` Entity에 변수명을 복수로 한다는걸 단수로 해놨네요.. 추후 변경사항이 있을 시 같이 변경해서 올리겠습니다. 없을 경우 변경 후 다시 올리겠습니다!

2021-11-11 14:04 UTC, kimdg1105 approved these changes

2021-11-11 14:04 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/model/PlayerAcquisition.kt
> +)
bids_log에서 언급한 널 처리 관련 부분입니다!

2021-11-15 00:06 UTC, philipjkim approved these changes
제가 한번 리뷰한 후 변경사항은 못봤는데, 일단 신뢰의 approve 드립니다.

2021-11-15 02:18 UTC, juyohan commented
@kimdg1105 테이블 변경건을 제가 안올렸었네요.. 이 부분 확인해주시고 말씀해주시면 바로 병합하겠습니다!

2021-11-15 13:17 UTC, kimdg1105 approved these changes

2021-11-15 13:42 UTC, merged