Feature/player scraping
fantasy-fans-ko/lad-be pull request #14
Opened 2021-11-18 19:45 UTC by juyohan

- 저장한 html의 파일을 스크래핑을 한 뒤, 각 요소에 접근해 데이터를 추출함.
- 추출한 데이터를 알맞게 매핑시켜 저장. (`Mapper`를 사용해야하나요?)
- 각 선수들의 사진을 프로젝트에 저장한 뒤, url로 접근을 할 수 있게 함.
- 선수들의 `사진 경로`와 `현재 랭킹`과 `이전의 랭킹`의 정보도 있으면 좋겠다라고 생각해 컬럼 추가.
- 따라서 V2 를 생성해 컬럼을 추가함.

2021-11-19 02:58 UTC, philipjkim requested changes
varchar size 를 전반적으로 키우는 작업 진행해주시고, 기타 커멘트 참고해서 변경해주세요.

2021-11-19 02:58 UTC, philipjkim commented on src/main/resources/db/migration/V1__createTable.sql
> +    `nickname`   varchar(25) NOT NULL COMMENT '입찰자 닉네임',
좀더 넉넉하게 `varchar(64)` 정도로 주시면 좋을거같네요.

2021-11-19 02:58 UTC, philipjkim commented on src/main/resources/db/migration/V1__createTable.sql
>      `name` varchar(36) DEFAULT NULL COMMENT '옥션 이름',
이것 역시 `varchar(128)` 정도로 여유있게 잡아주세요.

2021-11-19 02:58 UTC, philipjkim commented on src/main/resources/db/migration/V1__createTable.sql
> +    `name`           varchar(25) NOT NULL COMMENT '선수 이름',
전반적으로 컬럼 사이즈를 과도하게 작게 잡은 경향이 있어요. 이름 관련해서는 64자 정도는 되어야 나중에 골치아픈 상황이 줄어들겁니다. 기본적으로 16, 64, 256, 그 이상은 text 형으로 잡아주심 될듯하네요.

2021-11-19 02:58 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/service/ScrapingService.kt
> +        val resource = ClassPathResource("$DEFAULT_IMAGE_RESOURCES_PATH$afterPlayerName.png")
일단 지금은 이렇게 하고 나중에 2차드랩 후 여유 생기면 파일들은 s3 에 올리고 DB 컬럼엔 S3 url 저장하는 식으로 개선해보세요.

2021-11-19 02:58 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/model/Bidder.kt
> +@Table(name = "bidder")
`bidders` (복수) 로 바꿔주세요.

2021-11-19 02:58 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/service/ScrapingService.kt
> +    fun iterativeApproachToHtml(): Unit {
`: Unit` 은 제거하셔도 될겁니다.

2021-11-19 02:58 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/service/ScrapingService.kt
> +    private fun checkHealth(playerHealth: String) =
저라면 함수명을 `playerStatusOf` 정도로 할것같네요. `checkHealth` 는 건강을 체크한다는 뜻이지 player status 를 리턴한다는 의미로 보이지 않아요.

2021-11-19 04:02 UTC, juyohan commented on src/main/resources/db/migration/V1__createTable.sql
> +    `name`           varchar(25) NOT NULL COMMENT '선수 이름',
> 전반적으로 컬럼 사이즈를 과도하게 작게 잡은 경향이 있어요. 이름 관련해서는 64자 정도는 되어야 나중에 골치아픈 상황이 줄어들겁니다. 기본적으로 16, 64, 256, 그 이상은 text 형으로 잡아주심 될듯하네요.

sql 을 변경하려고 할 때, 이렇게 컬럼 `사이즈`를 변경하거나, 컬럼 `명`을 변경하거나, 컬럼 `자료형`을 변경하고자 할때는 V1의 Sql문을 건드려서 `checksum`을 변경하는게 좋은것인지, 아니면 `V1.0.1__modifyUser.sql` 이렇게 파일을 생성한 뒤, 관리를 하는게 좋은 것인지 잘 모르겠습니다.

지금은 V1을 변경을 하고 flyway_schema_history 에 접근해서 checksum 을 변경해서 관리하고 있습니다.

2021-11-19 04:13 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/service/ScrapingService.kt
> +    private fun checkHealth(playerHealth: String) =
혹시 함수명을 정하실 때, ~Of 라고 `Of`의 전치사는 언제 사용하시는건지 궁금합니다!

작명을 하는 과정에서 어떤식으로 접근해서 작명을 하는게 좋을지 너무 어렵네요.. 
추가로, `checkStatus`의 함수명은 별로일까요?

2021-11-19 04:30 UTC, philipjkim commented on src/main/resources/db/migration/V1__createTable.sql
> +    `name`           varchar(25) NOT NULL COMMENT '선수 이름',
`V3__modifyColumnSizes.sql` 정도면 명확히 어떤 일을 하는 sql 인지 이름이 나타내줄 수 있을것같네요. 이 sql 내에 players 외 모든 테이블들의 column size 를 조절해주세요.

2021-11-19 04:35 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/service/ScrapingService.kt
> +    private fun checkHealth(playerHealth: String) =
`playerStatusOf("GTD")` 와 같이 코드를 짜게 되면 GTD 의 플레이어 상태를 제공하는 함수로 자연어처럼 읽히니까요.

`checkStatus` 는 함수명만 보면 무언가를 리턴하는 함수가 아니라 status 를 인자로 받아서 체크(그게 뭔진 모르지만)하고 문제 있을경우 exception 발생 하는 것으로 받아들여지네요. Java 관례로 한다면 무언가를 리턴하는 경우 `getXXX`, `fetchXXX`, `convertXXX`, `generateXXX` 정도의 네이밍이 일반적이고, 제가 제안한 네이밍은 좀더 Kotlin 스러운 네이밍으로 봐주시면 되겠습니다.

naming 관련해서는 https://kotlinlang.org/docs/coding-conventions.html 도 한번 읽어보세요.

cc. @kimdg1105

2021-11-22 03:26 UTC, philipjkim approved these changes
Good job! 👏

2021-11-22 03:42 UTC, merged