[PR] Feature/list api
fantasy-fans-ko/lad-be pull request #16
Opened 2021-11-28 09:12 UTC by kimdg1105

#15 #

2021-12-04 11:18 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/repository/custom/impl/PlayerCustomRepositoryImpl.kt
> +    override fun selectById(id: Long): Player? {
카톡으로 말씀드린대로 서비스계층에서 DTO로 바뀌고 있습니다!

2021-12-04 12:18 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/controller/PlayerController.kt
> +    fun getPlayer(@RequestParam(required = true) id: Long?): CommonApiResponse? {
```suggestion
        @GetMapping
    fun getPlayer(@RequestParam id: Long): ResponseEntity<CommonApiResponse> {
        val body = playerService.readOne(id)?.let { success(it) }
        return ResponseEntity(body, HttpStatus.OK)
    }
```
해당 코멘트와 밑에까지 합하여 다음과 같이 변경해보았는데 어떨까요?

2021-12-04 12:41 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/dto/UserDto.kt
> +        data class UserDetail(
@QueryProjection을 적용한 부분은 DTO도 Q클래스 생성이 가능하여, Select절에 원하는 컬럼만 조회가 가능하다는 점을 확인하고자 한번 사용해본 것입니다.
현재 DTO로 변환하는 과정이 서비스 계층에서 모두 수행되고 있고, 페이지 내용 또한 Player 테이블의 모든 칼럼을 가져오기에 PlayerDTO @QueryProjection을 제거하도록 하겠습니다.

2021-12-04 12:42 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/common/web/CommonApiResponse.kt
> +@JsonInclude(JsonInclude.Include.NON_EMPTY)
넵 우선 NON_EMPTY는 삭제하겠습니다.

2021-12-04 12:50 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/controller/PlayerController.kt
> +    fun getPlayer(@RequestParam(required = true) id: Long?): CommonApiResponse? {
@kimdg1105 
좋네요~

2021-12-04 13:42 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/common/web/CommonApiResponse.kt
> +    val code: String,
상태로 남겨주는데 이거.. 필요할까요?? 궁금해서 여쭤봅니다!

2021-12-04 13:46 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/repository/custom/impl/PlayerCustomRepositoryImpl.kt
> +        val content: MutableList<Player> = queryResults.results
MutableList<>로 변경하신 이유가 혹시 있을까요?

2021-12-04 13:48 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/common/web/CommonApiResponse.kt
> +    val code: String,
해당 CommonApiResponse의 code, message는 HTTP 상태 외에도 서비스 로직의 자체적인 에러코드, 메세지가 관리되면 용이할 것 같다고 생각되어 추가해두었습니다. (USER001, PLAYER001 등)
불필요하다고 생각되면 제거하겠습니다!

2021-12-04 14:05 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/common/web/CommonApiResponse.kt
> +    val code: String,
세부적으로 나눌 때, 용이하겠네요!! 가지고가도 좋을 것 같아요!

2021-12-15 02:49 UTC, philipjkim requested changes
일단 코드가 많아서 몇가지 꼭지만 잡고 커멘트 드렸으니 보시고 고칠 부분들은 한번 고쳐보심 좋겠네요~

참고로 제가 querydsl 은 전혀 몰라서 repository 쪽 개선사항 커멘트대로 하면 동작하지 않을수도 있으니 그 부분은 한번 주의깊게 테스트해봐주세요.

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/common/dto/SearchPageDto.kt
> +        sort?.keys?.forEach(Consumer { k: String ->
L22-29 는 Java 의 forEach 대신 Kotlin 의 forEach 를 쓰면 좀더 간결해지겠네요:

```kotlin
        sort?.keys?.forEach {
            val order = if (sort[it] == Direction.ASC) Sort.Order.asc(it) else Sort.Order.desc(it)
            orders.add(order)
        }
```

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/common/web/CommonApiResponse.kt
> +    val timestamp: LocalDateTime = LocalDateTime.now(),
가급적이면 `LocalDateTime` 보다는 tz 정보를 포함하고 있는 `ZonedDateTime` 을 UTC 기준으로 사용하는게 좋을것 같아요. 저는 날짜/시간값을 응답으로 줄때는 무조건 unix epoch second (Long) 으로 줍니다. 그 값을 받은 f/e 에서는 그 값을 알아서 원하는 TZ 기준으로 변환해서 쓰도록요.

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/common/web/CommonApiResponse.kt
> +}
IntelliJ 의 Preference > General > On Save > Ensure every saved file ends with a line break 를 활성화해주시면 좋아요~

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/common/web/ErrorResponse.kt
> +    var httpMethod: String? = null,
요 두 값들은 not-null 이어도 될것같은데, nullable 로 정하신 이유가 있어요?

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/common/web/ErrorResponse.kt
> +    var errors: MutableList<Error>? = null,
가급적이면 MutableList 보다는 List 를 쓰는게 좋을듯해요. Kotlin 은 데이터를 다룰 때 immutabilty 가 default 에요~

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/controller/PlayerController.kt
> +    }
특별한 경우가 아니면 메소드의 return value 는 nullable 하지 않게 작성하는게 좋아요. 일단 `playerSerice.readAll()` 은 데이터가 없으면 null 이 아닌 empty list 를 주면 되구요, 그 메소드 return type 을 nun-null 로 바꾸면 아래와 같이 표현 가능해요. (function 의 return type 을 꼭 명시하지 않아도 됨)

```suggestion
    fun getAllPlayers() =
        ResponseEntity(success(playerService.readAll()), HttpStatus.OK)
```

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/controller/PlayerController.kt
> +        val body = playerService.readPage(request)?.let {
보통 `?.let` 을 쓰면 마지막에 `?:` 으로 null 인 케이스에 대한 대응 코드가 있어야해요. default 값을 주던가 에러를 내던가.

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/repository/custom/impl/UserCustomRepositoryImpl.kt
> +) : QuerydslRepositorySupport(User::class.java), UserCustomRepository {
querydsl 을 쓰는 경우는 보통 이렇게 인터페이스의 구현체를 만드나보네요~ 처음봐요 ㅎㅎ

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/service/PlayerService.kt
> +    }
```suggestion
    fun readAll() =
        playerRepository.selectAll().map { PlayerDto.Response.PlayerDetail().entityToDto(it) }
```

2021-12-15 02:49 UTC, philipjkim commented on src/main/kotlin/com/fantasy/ladbe/repository/custom/PlayerCustomRepository.kt
> +    fun selectAll(): List<Player>?
list, map 을 리턴하는 경우 값이 없으면 null 대신 empty collection 을 리턴하도록 해야 이 함수를 호출하는 쪽에서 편해요:

```suggestion
    fun selectAll(): List<Player>
```

2021-12-15 03:57 UTC, kimdg1105 commented
@philipjkim 리뷰 감사합니다~ 확인하고 수정하며 코멘트 달겠습니다!

2021-12-15 09:59 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/common/web/CommonApiResponse.kt
> +    val timestamp: LocalDateTime = LocalDateTime.now(),
@philipjkim 
질문있습니다!
- 날짜/시간값을 응답으로 줄 땐 아래와 같은 방식으로 보내면 되는걸까요?
```
val timestamp : Long = Instant.now().getEpochSecond()
```
- DB에 저장을 할 땐, LocalDateTime 보단 `ZonedDateTime` 으로 저장하라는 말씀으로 들리는데 이해한게 맞을까요?

2021-12-16 11:35 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/common/dto/SearchPageDto.kt
> +        sort?.keys?.forEach(Consumer { k: String ->
페이지 검색 Dto를 처음 만들 때 기존 자바 프로젝트의 코드를 참고하다 반영된 것 같네요..ㅠㅠ 감사합니다!

2021-12-16 11:38 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/common/web/CommonApiResponse.kt
> +    val timestamp: LocalDateTime = LocalDateTime.now(),
@philipjkim BE에서 전송하는 시간의 경우 모두 epoch time으로 공통화 하겠습니다!

2021-12-16 11:56 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/common/web/ErrorResponse.kt
> +    var httpMethod: String? = null,
@philipjkim 
```suggestion
    val httpStatus: String = "",
    val httpMethod: String = "",
    val message: String = "",
```

어제 요한님과 회의 후 해당 부분이 위와 같이 수정되었습니다!

2021-12-16 12:13 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/common/web/ErrorResponse.kt
> +    var errors: MutableList<Error>? = null,
해당 errors도 요한님과 회의 때 안쓰는 걸로 이야기하여 요한님 PR에서 삭제 되었습니다. (Kotlin 은 데이터를 다룰 때 immutabilty 가 default 기억하겠습니다!)

** 예외처리 코틀린 예제를 보면서 해당 코드를 작성했는데 아래와 같이  allErrors에 대해 하나씩 값을 더하는 예제여서 MutableList를 사용했던 것 같네요.

```
e.bindingResult.allErrors.forEach{ errorObject ->
            val error = Error().apply {
                this.field = (errorObject as FieldError).field
                this.message = errorObject.defaultMessage
                this.value = errorObject.rejectedValue
            }
        errors.add(error)
        }
```

2021-12-16 12:28 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/repository/custom/PlayerCustomRepository.kt
> +    fun selectAll(): List<Player>?
```
fun getAllPlayers() =
        ResponseEntity(success(playerService.readAll()), HttpStatus.OK)


fun readAll() =
        playerRepository.selectAll().map { PlayerDto.Response.PlayerDetail().entityToDto(it) }
```

가이드 주신 위 부분과 함께 수정하겠습니다. null 관련하여 헤매고 있었는데 설명해주셔서 명확하게 이해된 것 같네요..👍

2021-12-17 04:51 UTC, philipjkim approved these changes
👍

2021-12-17 07:42 UTC, juyohan approved these changes
좋아용~

2021-12-17 10:22 UTC, merged