Feature/kakao login
fantasy-fans-ko/lad-be pull request #21
Opened 2021-12-17 10:57 UTC by juyohan

## Title
#8 카카오 로그인 및 회원가입에 대한 PR 입니다.

## Feature
- 카카오 소셜을 통한 로그인 및 회원가입
- 자체적인 토큰 생성(Access Token)
- 토큰의 유효성 검사 및 여부 확인에 따른 예외처리

## Comment
- OAuth2 에 관한 정보들과 JWT의 secret key는 따로 application-oauth.yml & application-jwt.yml 로 관리하였습니다. (ignore 해두었습니다.)
- 로그인을 할 때마다, 회원의 이미지(프로필 사진)과 이메일의 정보는 계속적인 update 를 시켜놨습니다.
- 로그인을 했을 때의 f/e에게 보내주는 [응답](https://github.com/fantasy-fans-ko/lad-be/wiki/OAuth2-API)입니다.
- Refresh 토큰에 대한 필요성이 아직 느껴지지 않아, Access 토큰만 생성한 뒤 관리하였습니다.
- [예외처리](https://github.com/fantasy-fans-ko/lad-be/wiki/Error-Response)는 최대한 세부적으로 나눠 처리하였습니다.
- 혹시 파싱 같은 경우 aop를 사용하는건 어떨까요? 개인적으로 궁금합니다.

2021-12-19 05:52 UTC, kimdg1105 commented
고생 많으셨어요~  코멘트 궁금한 점은 밑에 인라인으로 추가했고, 코드 보면서 리뷰 달겠습니다~


> ## Comment
> * OAuth2 에 관한 정보들과 JWT의 secret key는 따로 application-oauth.yml & application-jwt.yml 로 관리하였습니다. (ignore 해두었습니다.)
 : **yml 파일을 여러 개 두는 것보다 둘을 합치는 것도 좋을 것 같습니다.**

> * Refresh 토큰에 대한 필요성이 아직 느껴지지 않아, Access 토큰만 생성한 뒤 관리하였습니다.
> * [예외처리](https://github.com/fantasy-fans-ko/lad-be/wiki/Error-Response)는 최대한 세부적으로 나눠 처리하였습니다.
 : **Refresh 토큰 기능 없이 엑세스 토큰의 시간을 충분히 늘려놓는 것이면 해당 예외는 우선 발생하지는 않는다는 전제인가요?**

2021-12-19 07:31 UTC, juyohan commented
> 고생 많으셨어요~ 코멘트 궁금한 점은 밑에 인라인으로 추가했고, 코드 보면서 리뷰 달겠습니다~
>    : **yml 파일을 여러 개 두는 것보다 둘을 합치는 것도 좋을 것 같습니다.**

조금 세분화하였는데 추후 수정사항이 있을 때, 하나로 합치겠습니다!
 
>    : **Refresh 토큰 기능 없이 엑세스 토큰의 시간을 충분히 늘려놓는 것이면 해당 예외는 우선 발생하지는 않는다는 전제인가요?**

기본 3시간으로 했습니다. 만약, 사용자가 로그인을 하고 3시간 동안 해당 페이지에 존재한다면, 예외가 발생이 됩니다!

2021-12-19 07:53 UTC, kimdg1105 requested changes

2021-12-19 07:53 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/model/Bidder.kt
> +//    val imageUrl : String = "",
주석은 제거해도 될 것 같습니다.

2021-12-19 07:53 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/service/UserService.kt
>          }
여기 익셉션은 제가 추가하겠습니다

2021-12-19 07:53 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/service/UserService.kt
> +    }
```suggestion
        val user: User = userRepository.selectByKakaoCode(kakaoCode)?.let {
            it.copy(
                id = it.id,
                kakaoCode = it.kakaoCode,
                kakaoImagePath = imagePath,
                kakaoEmail = email
            )
        }
            ?: User(
                kakaoCode = kakaoCode,
                kakaoEmail = email,
                kakaoImagePath = imagePath
            )
        return UserDto.Response.UserDetail()
            .entityToDto(userRepository.save(user))
    }
```

findOneByKakaoCode()의 사용이 updateOrSave에서만 있는 것이라면 하나로 합치는 것이 간결할 것 같습니다. (차후 findOneByKakaoCode()가 쓰이는 곳이 생길시 메소드 분리 해도 될 것 같아요)

2021-12-19 07:53 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/oauth/jwt/JwtFilter.kt
> +        throw NullPointerException()
```suggestion
        throw BusinessException(Exceptions.JWT_NULL_TOKEN)
```

NPE로 설정하신 이유가 있을까요? (없으시다면 저희가 쓰도록한 BusinessException...ㅎㅎ)

2021-12-19 08:00 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/model/Bidder.kt
> +//    val imageUrl : String = "",
사용자가 이미지 변경을 원할 경우 사용할 컬럼으로, 전에 이야기를 나눴었습니다!

옥션마다 프사를 다르게 하고 싶을 경우, 사용할 컬럼으로 지금은 사용하지 않지만 추후 사용을 위해 주석처리를 해두었습니다. TODO 로 빼두겠습니다!

2021-12-19 08:09 UTC, kimdg1105 commented on src/main/kotlin/com/fantasy/ladbe/model/Bidder.kt
> +//    val imageUrl : String = "",
아.. 전에 이야기를 한 부분인걸 깜빡했네요..ㅠ TODO 걸어놓으면 될 것 같아요!

2021-12-20 05:35 UTC, juyohan commented on src/main/kotlin/com/fantasy/ladbe/oauth/jwt/JwtFilter.kt
> +        throw NullPointerException()
@kimdg1105 
저희가 사용하려고 하는 BusinessException은 `Spring Context` 에서 사용이 되고있는 예외처리입니다.

JWT 는 `Filter` 단에서 진행이 되어 Spring Context에 들어가기 전, `Web Application` 에서 예외처리가 일어나게 됩니다.

제안하신 방식대로 진행하게 된다면, `BusinessException` 이 예외는 잡으나 (throw 로 직접 예외를 던졌기 때문입니다.), 그에대한 응답이 제대로 내려지지 않았습니다.
`ResponseEntity` 를 통해 응답을 보내려고 해도, ResponseEntity는 Spring Framework에서 제공하는 클래스이기 때문에 빈 응답만 내려오게 됩니다.

Web Application 단에서 생성된 예외를 바로 던져, Spring Context 에 도달하지 못하게 만들기 위해 NPE를 바로 던지게 해놨습니다.

2021-12-23 09:45 UTC, kimdg1105 approved these changes

2022-01-06 09:06 UTC, philipjkim approved these changes
나중에 리뷰는 여유있을때 보이는것들 조금씩 해볼게요~

2022-01-06 09:10 UTC, merged